/* マスターデータ（企業・職種・学部・大学などの選択肢） */

export const OTHER_OPTION = { value: "__other__", label: "その他（自由入力）" }

export const COMPANIES = [
  { value: "", label: "一般（企業指定なし）" },
  // IT / Web
  { value: "楽天", label: "楽天" },
  { value: "メルカリ", label: "メルカリ" },
  { value: "LINE", label: "LINE" },
  { value: "Google", label: "Google Japan" },
  { value: "Yahoo", label: "Yahoo Japan" },
  { value: "Amazon", label: "Amazon Japan" },
  { value: "Indeed", label: "Indeed" },
  { value: "CyberAgent", label: "CyberAgent" },
  { value: "DeNA", label: "DeNA" },
  { value: "MIXI", label: "MIXI" },
  // コンサル
  { value: "アクセンチュア", label: "アクセンチュア" },
  { value: "PwC", label: "PwC" },
  { value: "デロイト", label: "デロイト トーマツ" },
  { value: "EY", label: "EY (アーンスト・ヤング)" },
  { value: "KPMG", label: "KPMG" },
  { value: "BCG", label: "BCG" },
  { value: "マッキンゼー", label: "マッキンゼー・アンド・カンパニー" },
  // 金融
  { value: "三菱UFJ", label: "三菱UFJ銀行" },
  { value: "三井住友", label: "三井住友銀行" },
  { value: "みずほ", label: "みずほ銀行" },
  { value: "野村證券", label: "野村證券" },
  { value: "SMBC日興", label: "SMBC日興証券" },
  // メーカー
  { value: "ソニー", label: "ソニー" },
  { value: "トヨタ", label: "トヨタ自動車" },
  { value: "パナソニック", label: "パナソニック" },
  { value: "日立", label: "日立製作所" },
  { value: "キーエンス", label: "キーエンス" },
  // その他
  { value: "電通", label: "電通" },
  { value: "博報堂", label: "博報堂" },
  { value: "日本郵政", label: "日本郵政" },
  OTHER_OPTION,
]

export const POSITIONS = [
  { value: "", label: "未選択" },
  OTHER_OPTION,
  { value: "エンジニア", label: "エンジニア（SE・プログラマー）" },
  { value: "営業", label: "営業" },
  { value: "マーケティング", label: "マーケティング" },
  { value: "企画", label: "企画・事業開発" },
  { value: "人事", label: "人事" },
  { value: "経理・財務", label: "経理・財務" },
  { value: "法務", label: "法務" },
  { value: "広報", label: "広報・PR" },
  { value: "デザイナー", label: "デザイナー" },
  { value: "データサイエンティスト", label: "データサイエンティスト" },
  { value: "コンサルタント", label: "コンサルタント" },
  { value: "総合職", label: "総合職" },
  OTHER_OPTION,
]

export const MAJORS = [
  { value: "", label: "未選択" },
  OTHER_OPTION,
  { value: "文学", label: "文学部／人文科学" },
  { value: "法学", label: "法学部／法律" },
  { value: "経済学", label: "経済学部／経済学" },
  { value: "経営学", label: "経営学部／商学" },
  { value: "社会学", label: "社会学部／社会科学" },
  { value: "心理学", label: "心理学部／心理学" },
  { value: "情報工学", label: "情報工学部／コンピュータ科学" },
  { value: "機械工学", label: "機械工学部" },
  { value: "電気電子", label: "電気電子工学部" },
  { value: "建築", label: "建築学部" },
  { value: "化学", label: "化学・応用化学" },
  { value: "生物", label: "生物・生命科学" },
  { value: "医学", label: "医学部" },
  { value: "薬学", label: "薬学部" },
  { value: "農学", label: "農学部" },
  { value: "国際", label: "国際学部" },
  { value: "教育", label: "教育学部" },
  OTHER_OPTION,
]

export const UNIVERSITIES = [
  { value: "", label: "未選択" },
  OTHER_OPTION,
  // 国立
  { value: "東京大学", label: "東京大学" },
  { value: "京都大学", label: "京都大学" },
  { value: "大阪大学", label: "大阪大学" },
  { value: "東京工業大学", label: "東京工業大学" },
  { value: "東北大学", label: "東北大学" },
  { value: "名古屋大学", label: "名古屋大学" },
  { value: "九州大学", label: "九州大学" },
  { value: "北海道大学", label: "北海道大学" },
  { value: "筑波大学", label: "筑波大学" },
  { value: "神戸大学", label: "神戸大学" },
  { value: "一橋大学", label: "一橋大学" },
  { value: "東京外国語大学", label: "東京外国語大学" },
  { value: "千葉大学", label: "千葉大学" },
  { value: "横浜国立大学", label: "横浜国立大学" },
  // 私立
  { value: "早稲田大学", label: "早稲田大学" },
  { value: "慶應義塾大学", label: "慶應義塾大学" },
  { value: "上智大学", label: "上智大学" },
  { value: "国際基督教大学", label: "国際基督教大学 (ICU)" },
  { value: "明治大学", label: "明治大学" },
  { value: "青山学院大学", label: "青山学院大学" },
  { value: "立教大学", label: "立教大学" },
  { value: "中央大学", label: "中央大学" },
  { value: "法政大学", label: "法政大学" },
  { value: "同志社大学", label: "同志社大学" },
  { value: "立命館大学", label: "立命館大学" },
  { value: "関西学院大学", label: "関西学院大学" },
  { value: "関西大学", label: "関西大学" },
  { value: "東京理科大学", label: "東京理科大学" },
  { value: "芝浦工業大学", label: "芝浦工業大学" },
  { value: "明治学院大学", label: "明治学院大学" },
  { value: "その他国立", label: "その他国立大学" },
  { value: "その他私立", label: "その他私立大学" },
  { value: "海外大学", label: "海外の大学" },
  { value: "専門学校", label: "専門学校" },
  OTHER_OPTION,
]

export const INDUSTRIES = [
  { value: "", label: "未選択" },
  OTHER_OPTION,
  { value: "IT・通信", label: "IT・通信" },
  { value: "金融", label: "金融・銀行・証券" },
  { value: "コンサル", label: "コンサルティング" },
  { value: "メーカー", label: "メーカー（製造業）" },
  { value: "商社", label: "商社" },
  { value: "広告", label: "広告・出版・マスコミ" },
  { value: "不動産", label: "不動産" },
  { value: "建設", label: "建設・設備" },
  { value: "エネルギー", label: "エネルギー" },
  { value: "医療", label: "医療・製薬" },
  { value: "教育", label: "教育" },
  { value: "旅行", label: "旅行・運輸" },
  { value: "官公庁", label: "官公庁・公社" },
  OTHER_OPTION,
]
